name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Run tests
        run: make test

      - name: Build binaries
        run: make build
